name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Kaynak kodu çek
      - name: Checkout code
        uses: actions/checkout@v3

      # Docker Buildx'i ayarla
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Docker Hub'a giriş yap
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # ARM64 mimarisi için imajı oluştur ve Docker Hub'a push et
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/your-repo-name:latest
